const pizzaJson = [
  {
    id: 1,
    category: "TRADICIONAL",
    name: "MARGUERITA",
    img: "images/pizza.png",
    description: "Tomate, manjericão e orégano",
    price: [25.0, 32.0, 42.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "10 fatias", "12 fatias"],
  },
  {
    id: 2,
    category: "TRADICIONAL",
    name: "PORTUGUESA",
    img: "images/pizza.png",
    description:
      "Calabresa, presunto, bacon, cebola, pimentão, ovos, e orégano",
    price: [25.0, 32.0, 42.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "10 fatias", "12 fatias"],
  },
  {
    id: 3,
    category: "TRADICIONAL",
    name: "CALABRESA",
    img: "images/pizza.png",
    description: "Molho de tomate, mussarela, tomate, manjericão e orégano",
    price: [25.0, 32.0, 42.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "10 fatias", "12 fatias"],
  },
  {
    id: 4,
    category: "TRADICIONAL",
    name: "BAIANA",
    img: "images/pizza.png",
    description: "Calabresa, pimenta calabresa, bacon e orégano",
    price: [25.0, 32.0, 42.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "10 fatias", "12 fatias"],
  },
  {
    id: 5,
    category: "TRADICIONAL",
    name: "FRANGO",
    img: "images/pizza.png",
    description: "Frango, milho e orégano",
    price: [25.0, 32.0, 42.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "10 fatias", "12 fatias"],
  },
  {
    id: 6,
    category: "TRADICIONAL",
    name: "CARNE DE SOL",
    img: "images/pizza.png",
    description: "Carne de sol desfiada, cebola e orégano",
    price: [25.0, 32.0, 42.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "10 fatias", "12 fatias"],
  },
  {
    id: 7,
    category: "TRADICIONAL",
    name: "MISTA",
    img: "images/pizza.png",
    description: "Presunto e orégano",
    price: [25.0, 32.0, 42.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "10 fatias", "12 fatias"],
  },
  {
    id: 8,
    category: "TRADICIONAL",
    name: "NAPOLITANA",
    img: "images/pizza.png",
    description: "Tomate, pimentão, azeitona e orégano",
    price: [25.0, 32.0, 42.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "10 fatias", "12 fatias"],
  },
  {
    id: 9,
    category: "TRADICIONAL",
    name: "PALMITO",
    img: "images/pizza.png",
    description: "Palmito, tomate e orégano",
    price: [25.0, 32.0, 42.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "10 fatias", "12 fatias"],
  },
  {
    id: 10,
    category: "PREMIUM",
    name: "CARNE DE SOL COM CATUPIRY",
    img: "images/pizza.png",
    description: "Carne de sol, catupiry e orégano",
    price: [30.0, 35.0, 45.0, 65.0],
    sizes: ["6 fatias", "8 fatias", "10 fatias", "12 fatias"],
  },
  {
    id: 11,
    category: "PREMIUM",
    name: "FRANGO COM CATUPIRY",
    img: "images/pizza.png",
    description: "Frango, catupiry e orégano",
    price: [25.0, 32.0, 42.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "10 fatias", "12 fatias"],
  },
  {
    id: 12,
    category: "PREMIUM",
    name: "MODA DA CASA",
    img: "images/pizza.png",
    description: "Presunto, lombo defumado, bacon, ervilha e orégano",
    price: [25.0, 32.0, 42.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "10 fatias", "12 fatias"],
  },
  {
    id: 13,
    category: "PREMIUM",
    name: "4 QUEIJOS",
    img: "images/pizza.png",
    description: "Mussarela, cheddar, queijo parmesão, catupiry e orégano",
    price: [25.0, 32.0, 42.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "10 fatias", "12 fatias"],
  },
  {
    id: 14,
    category: "PREMIUM",
    name: "CAMARÃO",
    img: "images/pizza.png",
    description: "Camarão, azeitona e orégano",
    price: [25.0, 32.0, 42.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "10 fatias", "12 fatias"],
  },
  {
    id: 15,
    category: "PREMIUM",
    name: "CAMARÃO COM CATUPIRY",
    img: "images/pizza.png",
    description: "Camarão, catupiry e orégano",
    price: [25.0, 34.0, 45.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "10 fatias", "12 fatias"],
  },
  {
    id: 16,
    category: "PREMIUM",
    name: "PORTUGUESA ESPECIAL",
    img: "images/pizza.png",
    description: "Presunto, bacon, ovos, cebola, pimentão, azeitonas e orégano",
    price: [25.0, 34.0, 45.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "10 fatias", "12 fatias"],
  },
  {
    id: 17,
    category: "DOCES",
    name: "BRIGADEIRO",
    img: "images/pizza.png",
    description: "Chocolate, brigadeiro e granulado",
    price: [25.0, 32.0, 42.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "10 fatias", "12 fatias"],
  },
  {
    id: 18,
    category: "DOCES",
    name: "BANANA COM CANELA",
    img: "images/pizza.png",
    description: "Banana, canela e açúcar",
    price: [25.0, 32.0, 42.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "10 fatias", "12 fatias"],
  },
  {
    id: 19,
    category: "DOCES",
    name: "SENSAÇÃO",
    img: "images/pizza.png",
    description: "Morango, chocolate e chantilly",
    price: [25.0, 32.0, 42.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "10 fatias", "12 fatias"],
  },
  {
    id: 20,
    category: "DOCES",
    name: "ROMEU E JULIETA",
    img: "images/pizza.png",
    description: "Queijo mussarela, goiabada cremosa e orégano",
    price: [25.0, 32.0, 42.0, 60.0],
    sizes: ["6 fatias", "8 fatias", "10 fatias", "12 fatias"],
  },
];
